{"name": "test_logging_with_valid_username_invalid_password", "status": "passed", "start": 1711016942172, "stop": 1711016943738, "uuid": "54dd038c-b4ef-405c-be4b-f2c4f44b153a", "historyId": "a1c734f0eb02a7ad14a30dfd3c17252f", "testCaseId": "a1c734f0eb02a7ad14a30dfd3c17252f", "fullName": "tests.Login_Test.TestLogin#test_logging_with_valid_username_invalid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "Login_Test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4VA98U9"}, {"name": "thread", "value": "16988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Login_Test"}]}